---
title: '4: Data Enrichment'
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

* * *

A pivotal operation was undertaken to enhance the usability of the dataset. Specifically, within the business dataframe, nested JSON files underwent a transformation into CSV format. This process involved extracting each nested key from the JSON structure and assigning it to a new column in the CSV file. By doing so, the dataset's complexity was mitigated, making it more accessible for analysis and interpretation. This restructuring facilitated easier navigation through the data, enabling us to extract valuable insights with greater efficiency. Additionally, it streamlined subsequent processing steps, such as data cleaning, visualization, and statistical analysis. Overall, this transformation represented a significant milestone in optimizing the dataset for comprehensive Yelp business reviews analysis.

The implementation can be found in the Data Processing section of [Yelp_Data Processing](https://github.com/stats-at-Rutgers/group-project-collective_creators/blob/main/Yelp_Data%20Processing.ipynb) notebook.