on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with: # This is so the Pipe loads the LFS-tracked files
          lfs: true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Setup Python 3.12.2
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
          cache: 'pip'
      - run: pip install jupyter

      # -run: git lfs install
      # -run: git lfs pull

      - name: Install all necessary packages
        run: pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}